version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: orchestrator_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "try { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) } catch(e) {} rs.status().ok ? quit(0) : quit(1)"]
      interval: 10s
      start_period: 30s

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: orchestrator_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  webhook-simulator:
    image: kennethreitz/httpbin
    container_name: webhook-simulator
    ports:
      - "8080:80"

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data

  api:
    build:
      context: .
      dockerfile: src/JobOrchestrator.Api/Dockerfile
    container_name: joborchestrator_api
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017/?replicaSet=rs0
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      seq:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: src/JobOrchestrator.Worker/Dockerfile
    container_name: joborchestrator-worker
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017/?replicaSet=rs0
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      seq:
        condition: service_started

volumes:
  mongo_data:
  seq_data: